materia(nome, [palavras_chaves], area_conhecimento, horas, ementa).

materia('Computação Básica', ['Resolução de Problemas', 'Matemática', 'Programação', 'Algoritmo', 'Computação'], 'Engenharias', 90, 'Histórico do computador computadores e resolução de problemas estruturas de decisão vetores e matrizes cadeias de caracteres sub-algoritmos: funções e procedimentos estilo de programação particularidades da linguagem pascal.').

materia('Estruturas de Dados', ['Matemática', 'Programação', 'Memória', 'Estrutura de Dados', 'Resolução de Problemas'], 'Software', 60, 'Gerenciamento dinâmico da memória. listas. pilhas. filas. árvores. ordenação e pesquisa.pesquisa em árvores. grafos. análise e aplicação de estruturas avançadas em problemas de programação. resolução de problemas. aplicações em problemas ambientais.').

materia('Projeto e Análise de Algoritmos', ['Resolução de Problemas', 'Matemática', 'Programação', 'Algoritmo', 'Complexidade'], 'Software', 60, 'Fundamentos matemáticos para análise de algoritmos análise assintótica de algoritmos paradigmas de projeto de algoritmos algoritmos eficientes para ordenação, comparação de sequências, problemas em grafos fundamentos de complexidade computacional, redução entre problemas, classes p e np, problemas np-completos.').

materia('Introdução ao Desenvolvimento de Jogos', ['Jogos', 'Colisão', 'Programação', 'Arquitetura - Software', 'Desenvolvimento de Software', 'Linguagens de Programação'], 'Software', 60, 'Tópicos introdutórios ao desenvolvimento de jogos. linguagens e arquitetura de jogos. fundamentos de programação aplicados ao desenvolvimento de jogos. tópicos avançados em desenvolvimento de jogos, tais como detecção de colisão e inteligência artificial.').

materia('Técnicas de Programação 1', ['Orientação a Objetos', 'Programação'], 'Software', 60, 'Decomposição de problemas usando classes e objetos. reuso com herança e composição de classes. polimorfismo por subtipos/parametrizado. tratamento de exceções. técnicas de desenho e programação oo. tópicos especiais (distribuição, concorrência). técnicas avançadas de modularização.').

materia('Sistemas Digitais 1', ['Circuitos Lógicos', 'Álgebra', 'Aritmética Digital', 'Sistemas', 'Lógica', 'Matemática'], 'Software', 90, 'Sistemas de numeração e códigos portas lógicas e álgebra booleana circuitos lógicos combinacionais vhdl aritmética digital: operações e circuitos, circuitos lógicos msi princípios de sistemas sequenciais.').

materia('Sistemas Digitais 2', ['Arquitetura - Hardware', 'Memória', 'Programação'], 'Software', 90, 'Flip-flops máquinas de estado síncronas máquinas de estado assíncronas registradores e contadores memória controladores programáveis (seqüenciadores) microcontroladores.').

materia('Fenômenos de Transporte', ['Fluídos', 'Física', 'Matemática', 'Energia', 'Termodinâmica'], 'Energia', 75, 'Mecânica dos fluidos: propriedades dos fluidos estática dos fluidos -manometria, forças em superfícies planas e curvas, empuxo, estabilidade de corpos submersos e flutuantes estudo dos fluidos em movimento - tipos de escoamento, conceitos de sistema e volume de controle, conservação de massa,equação de energia e suas aplicações, equação de bernoulli, linhas de gradiente de energia, equação da quantidade de movimento e suas aplicações análise dimensional e semelhança dinâmica escoamentos internos - efeitos de viscosidade, escoamentos laminar e turbulento, perdas distribuídas e localizadas,escoamento permanente à superfície livre máquinas de fluxo - teoria, diagrama de velocidades, equações teóricas das máquinas, aplicações simples de curvas de bombas e curvas de sistema escoamentos externos escoamento de fluidos compressíveis. transferência de massa: difusão molecular e difusividade transferência de massa por convecção e difusão turbulenta. transmissão de calor.').

materia('Prática Desportiva', ['Esporte', 'Saúde'], 'Engenharias', 30, 'Conhecimentos teórico-práticos sobre atividades físicas, corporais e esportivas.conceito de qualidade de vida e benefícios da prática regular e orientada de atividade física para promoção e manutenção da saúde. recomendações e cuidados para uma prática adequada de exercícios físicos. integração social entre os estudantes de diversos cursos na modalidade escolhida.').

materia('Contratação de Serviços de Tecnologia da Informação', ['Tecnologia', 'Administração', 'Processos', 'Qualidade'], 'Software', 60, 'Importância das contratações de ti na administração pública federal. processo de contratação no contexto da governança de ti. o pcsti - processo de contratação de serviços de tecnologia da informação para organizações públicas. a importância da qualidade de processo de software em contratações de serviços de software.').

materia('Técnicas de Medição Funcional e Estimativas de Software', ['Medição', 'Matemática', 'Análise'], 'Software', 60, 'Técnicas de medição: análise de pontos de função, pontos de caso de uso, cosmic function points. medição e estimativa de tamanho de software. técnica nesma. estimativas de esforço e prazo em projetos de software.').

materia('Fundamentos de Equações Diferenciais para Engenharia', ['Equações', 'Matemática'], 'Engenharias', 60, 'Faz parte da disciplina: 1.equações diferenciais parciais de primeira ordem-leis de conservação (método das características) 2.equações diferenciais parciais de segunda ordem em domínios limitados-separação de variáveis-série de fourier 3.teoria de sturm-liouville-expansão por séries ortogonais-equações não-homogêneas 4.transformadas discretas-funções de bessel 5.equações diferenciais parciais de segunda ordem em domínios ilimitados-transformada de fourier 6.introdução às equações diferenciais não-lineares').

materia('Confiabilidade de Componentes e Sistemas', ['Sistemas', 'Segurança', 'Normas'], 'Engenharias', 60, 'Apresentação da teoria da confiabilidade estrutural. princípios e conceitos de segurança estrutural coeficiente de segurança e normas bases da teoria da confiabilidade avaliação da segurança estrutural de peças existentes métodos de avaliação da confiabilidade e estudo de casos elementares.').

materia('Sistemas Aeroespaciais', ['Aerodinâmica', 'Física', 'Matemática'], 'Aeroespacial', 60, 'Introduz princípios fundamentais da aerodinâmica, da propulsão e da mecânica orbital para a análise de projetos de aviões, foguetes e naves espaciais tópicos em aeronaves incluem introdução: ao desempenho de cruzeiro, ao projeto da asa, à propulsão, à estabilidade, ao controle e às estruturas tópicos em espaçonaves incluem introdução: ao projeto e teste de foguetes espaciais, à propulsão, a órbitas e missões, aos sistemas de lançamento e aos subsistemas de espaçonaves.').

materia('Fundamentos de Arquitetura de Software', ['Modelagem', 'Arquitetura - Software'], 'Software', 60, 'A importância da arquitetura de software reside no fato de permitir a criação de sistemas preditivos e organizados logicamente. Projetar a arquitetura de um software é vital para que os interesses de todos os agentes envolvidos sejam considerados.').

materia('Princípios de Robótica Educacional', ['Resolução de Problemas em Time', 'Robótica'], 'Software', 60, 'Robótica educacional é um método de aprendizagem focado na pesquisa, descoberta e construção de uma máquina como resultado da aquisição de conhecimentos. Ele depende do uso de kits prontos de montagem ou transformação de outros materiais, como sucata e itens recicláveis para compor as peças do robô.').

materia('Programação para Competições', ['Algoritmo', 'Competição', 'Resolução de Problemas'], 'Software', 60, 'Robótica educacional é um método de aprendizagem focado na pesquisa, descoberta e construção de uma máquina como resultado da aquisição de conhecimentos. Ele depende do uso de kits prontos de montagem ou transformação de outros materiais, como sucata e itens recicláveis para compor as peças do robô.').

materia('Pré-Cálculo para Engenharia', ['Matemática', 'Cálculo', 'Álgebra'], 'Engenharias', 60, 'Conteúdos como: Frações, potenciação e radiciação; Expressões numéricas, algébricas e fatoração; Números reais e funções; Funções polinomiais, raízes, gráficos e divisão de polinômios; Estudo do triângulo e trigonometria no triângulo retângulo; Funções trigonométricas; Vetores (Álgebra vetorial, produto escalar e decomposição de vetores); Matrizes e determinantes; Solução de sistemas lineares.').

materia('Aerodinâmica de Sistemas Aeroespaciais', ['Aerodinâmica'], 'Aeroespacial', 75, 'Introduz princípios fundamentais da aerodinâmica de sistemas aeroespaciais: veículos aéreos e espaciais, estudando elementos de escoamentos de alta e baixa velocidade, internos e externos Tópicos em escoamentos incompressíveis incluem: teoria e modelagem escoamentos incompressíveis bidimensionais e tridimensionais, e camada limite laminar e turbulenta aplicadas a aerofólios e asas Tópicos em escoamentos compressíveis incluem: teoria e modelagem de propagação de ondas de choque e camada limite compressível aplicadas a aerofólios, asas, bocais, difusores e túneis de vento.').

materia('Tópicos Especiais em Jogos Digitais', ['Jogos', 'Inovação', 'Gameficação'], 'Software', 60, 'Ementa variável, abordando temas que solicitam uma reflexão acadêmica, voltada para questões práticas. A cada semestre a disciplina terá uma ementa específica, a ser definida pelo professor responsável.').

materia('Dinâmica dos Gases para Sistemas Aeroespaciais', ['Aerodinâmica'], 'Aeroespacial', 60, 'Escoamentos supersônicos Escoamentos hipersônicos Equilíbrio e não-equilíbrio, escoamentos congelados e escoamentos reativos Camada limite e turbulência, escoamentos rarefeitos.').

materia('Projeto de Sistemas de Controle', ['Matemática', 'Resolução de Problemas'], 'Engenharias', 60, 'Projeto no Espaço de Estados.1.1. Introdução1.2. Atribuição dos autovalores1.3. Controlabilidade1.4. Observabilidade1.5. Projeto do observador1.6. Regulador quadrático linear.2 - Estimação do estado.2.1. Introdução2.2. Estimação dos mínimos quadrados2.3. O filtro de Kalman2.4. Os filtros de Kalman não-lineares: filtro de Kalman Extendido, Unscented Filter2.5. Aplicaçoes do filtro de Kalman: navegaçãoe fusão de sensores.3 - Controle ótimo.3.1. Introdução3.2. Calculo variacional3.3. Princípio do mínimo de Pontryagin3.4. Problemas clássicos de controle ótimo3.5. Aplicaçoes de controle ótimo: guiagem ótima e rendez-vous.').

materia('Mecânica do Vôo', ['Aerodinâmica', 'Equações'], 'Aeroespacial', 60, 'Equacionamento do movimento de uma aeronave considerada como corpo rígido: análise dinâmica e cinemática Conceitos fundamentais da dinâmica e controle de atitude de aeronaves Construção do modelo da aeronave e superfícies de controle: aerodinâmica básica, forças e momentos, o modelo não-linear da aeronave, modelos lineares e derivadas de estabilidade e as relações com o desempenho e projeto da aeronave Ferramentas Analíticas e Computacionais: modelos dos subsistemas, modelos de aeronave para simulação, vôo permanente compensado, solução numérica das equações de estado, linearização, simulação com equações lineares invariantes no tempo, controle com realimentação.').

materia('Métodos e Técnicas da Escrita Científica', ['Escrita Científica', 'Comunicação'], 'Engenharias', 60, 'Métodos e Técnicas em Escrita Científica: Introduzir o estudante os conhecimentos técnicos necessários a elaboração e desenvolvimento de textos e artigos científicos na área de engenharia. Integrar os conhecimentos e as habilidades técnicas adquiridas ao longo do curso de graduação na solução de problemas, por meio do desenvolvimento da escrita cientifica. Apresentar os fundamentos metodológicos do processo da escrita cientifica. Compreender as técnicas e métodos da escrita científica. Desenvolver a capacidade de comunicação técnica, escrita e oral e desenvolver a capacidade de pensamento crítico independente de investigação e autoaprendizagem.').

materia('Cálculo para Engenharia 2', ['Matemática', 'Cálculo', 'Equações'], 'Engenharias', 60, 'Técnicas de integração, aplicações da integral,sequência de séries numéricas, limite e continuidade de funções variáveis, derivada parcial;').

materia('Equações Diferenciais Ordinárias', ['Matemática', 'Cálculo', 'Equações'], 'Engenharias', 60, 'Equações diferenciais ordinárias de 1 ordem, aspectos geométricos, teoremas de existência de soluções, equações de 2 ordem, resolução de equações utilizando o método das séries de potências, transformada de Laplace e outros métodos.').

materia('Cálculo para Engenharia 3', ['Matemática', 'Cálculo', 'Equações'], 'Engenharias', 60, 'Calculo de valores máximos e mínimos, sistemas de coordenadas geométricas, gráficos de funçõem em coordenadas polares, integrais múltiplas e suas aplicações, cálculo de integrais de linha por parametrização, Teorema de Green, integrais de superfícies.').

materia('Processamento Digital de Sinais Financeiros', ['Circuitos Lógicos'], 'Eletrônica', 60, 'Fundamentos da Análises Gráfica, Técnica e Quantitativa; Modelagem Estocástica do Preço com o Movimento Browniano Geométrico; Teoria do Portfólio Moderno de Markovitz; Estimadores de Tendência, Reversão e Volatilidade; Operações Long & Short com Cointegração; Implementação de Indicadores e Expert Advisor no Metatrader; Técnicas de Otimização e de Backtest; Infraestrutura de Hardware e Software para Algo Trading.').

materia('Tópicos Especiais de Engenharia de Software', ['Resolução de Problemas em Time', 'Empreendedorismo'], 'Software', 60, 'Os temas e técnicas não tratadas nas disciplinas sistematizadas do curso, com o avanço rápido das tecnologias da área, serão tratados aqueles assuntos que solicitam uma reflexão acadêmica, voltada para questões práticas.').

materia('Materiais de Construção de Engenharia', ['Energia', 'Química'], 'Energia', 60, 'Estrutura atômica e ligações químicas, estrutura dos sólidos cristalinos, imperfeições em sólidos, propriedades mecânicas, diagramas de fase, processamento térmico em ligas metálicas, ligas metálicas, estruturas e propriedades das cerâmicas, estruturas e propriedades polimétricas, materiais compósicos, seleção de materiais para engenharia.').

materia('Gestão Ambiental no Setor Energético', ['Energia', 'Sustentabilidade'], 'Energia', 60, 'O problema ambiental e o desenvolvimento sustentável: a evolução histórica e política da questão ambiental no Brasil.Gestão ambiental: conceitos, histórico e paradigma, instrumentos de gestão ambiental, estudo de caso.').

materia('Fundamentos da Teoria Eletromagnética', ['Eletromagnetismo'], 'Eletrônica', 90, 'Conceitos básicos de análise vetorial no estudo de eletromagnetismoEletrostática. Dielétricos e capacitânciaPrimeira equação de Maxell. Corrente elétrica. Equação de continuidade. Campo magnéticoLei de Ampere. Indutância. Curva de saturação do ferro. Permeabilidade. Imãs. Lei de FaradayEnergia no campo e no campo magnético. Equações de MaxwellOndas eletromagnéticasVetor de Poynting.').

materia('Física Moderna', ['Física'], 'Aeroespacial', 90, 'Teoria da relatividade restrita, os raios catódicos e radioatividade, radiação de corpo negro e a concepção corpuscular da luz, modelos atômicos clássicos, o átomo de Bohr, a mecânica quântica ondulatória da Equação de Schrodinger.').

materia('Engenharia de Segurança do Trabalho', ['Segurança', 'Processos', 'Resolução de Problemas em Time'], 'Engenharias', 30, 'Interligação entre as varias engenharias e a engenharia de seguranca do trabalho.').

materia('Ergonomia do Produto', ['Energia', 'Componentes Automotivos'], 'Engenharias', 60, 'Antropometria e dimensionamento do posto de trabalho Biomecânica, aspectos da postura e movimentos do corpo, esforço físico Aspectos sensoriais e cognição, concepção de dispositivos de informação Fatores ambientais no trabalho e o espaço de trabalho Projeto com ênfase em Conforto Ergonomia e Design de produtos Package Automotivo e Normas Técnicas Living Space (adequação dos espaços de interior) Concepção de assentos Concepção de dispositivos de informação aplicados aos veículos automotores Concepção de dispositivos de comando Concepção de interior de um veículo Aspectos visuais na condução de veículos automotores Validação de projeto de interior.').

materia('Mecânica dos Sólidos 1 para Engenharia', ['Matemática', 'Física', 'Sólidos'], 'Engenharias', 60, 'Equilíbrio dos corpos rígidos Análise estrutural Tensões e deformações Deformação por esforço axial Geometria das massas.').

materia('Introdução ao Design e Concepção de Veículos', ['Desenho', 'Veículos'], 'Automotiva', 60, 'Técnicas de desenho e ilustração- sketches manuais e digitais, história do design automotivo-evolução tecnológica, economia e sociedade, ergonomia do Produto-Introdução à Ergonomia/Projeto de "Hard Points" e função dos sistemas/Conforto e Segurança, design de interiores-relação com o usuário final/Materiais/Tendências de Mercado5- Mock-Up Eletrônico-Modelagem de um produto/Integração de sistemas/Apresentação final de produto, laboratório da Forma.').

materia('Combustíveis e Biocombustíveis', ['Fluídos', 'Energia'], 'Engenharias', 60, '- Combustíveis fósseis- Energia renovável- Biodiesel- Bioetanol- Células combustíveis- Contexto macroeconômico dos biocombustíveis').

materia('Estruturas Matemáticas para Computação', ['Matemática', 'Algoritmo', 'Lógica'], 'Software', 60, 'Lógica Proposicional, Teoria dos Conjuntos, demonstração de teoremas II,análise combinatória,permutações,combinações,arranjos.').

materia('Processo de Desenvolvimento de Software', ['Processos', 'Desenvolvimento de Software'], 'Software', 60, 'Definição das fases de um processo de desenvolvimento de Software e das atividades de apoio.').

materia('Sistemas Automotivos', ['Veículos', 'Motores'], 'Automotiva', 60, 'Alguns dos assustos abortados pela disciplina: - Conceitos básicos dos sistemas que compõem o veículo - Chassi e carroceria - Sistema de suspensão - Sistema de controle de estabilidade de veículos - Sistema de freio - Sistema de controle de tração - Sistema de potência - Sistemas de injeção eletrônica - Sistema de transmissão.').

materia('Fontes de Energia e Tecnologias de Conversão', ['Termodinâmica', 'Energia', 'Transformação de Energia', 'Fontes de Energia'], 'Energia', 60, 'Fundamentos teóricos: conversão de energia, calor e trabalho, leis da Termodinâmica- Principais fontes e tecnologias de transformação de energia: solar, combustíveis, fósseis, fotovoltaica, eólica, hídricas, biomassa, geotérmica, nuclear - A questão das fontes energéticas no Brasil.').

materia('Técnicas de Programação', ['Programação', 'Documentação', 'Segurança', 'Algoritmo'], 'Software', 60, 'Programação Defensiva e Programação por Contrato.Documentação, Tratamento de Erros e Depuração de código.Programação Segura.Boas Práticas de Programação e Projeto.Programação Concorrente e Paralela.Otimização de Programas e Análise de Desempenho.').

materia('Desenvolvimento Sustentável', ['Energia', 'Sustentabilidade', 'Social'], 'Energia', 60, 'A evolução da discussão dos problemas ambientais e suas repercussões na formação política brasileira. Introdução ao Conceito Desenvolvimento Sustentável. Sistemas de indicadores de Sustentabilidade. Conflitos Socioambientais.').

materia('Engenharia de Petróleo e Gás', ['Energia', 'Petróleo', 'Fluídos'], 'Energia', 60, 'Aborda assuntos como: O petróleo - Noções de Engenharia de Petróleo - Prospecção de Petróleo - Perfuração - Avaliação de Formações - Completação - Reservatórios - Elevação - Processamento primário de fluidos - Refino do petróleo').

materia('Mecânica dos Sólidos 2 para Engenharia', ['Física', 'Sólidos'], 'Engenharias', 60, 'Aborda assuntos como: - Análise de Tensões - Teoria da elasticidade - Critérios de falha - Deflexão de vigas').